### ISSUE TITLE
BY-73  As a developer, I need to update the wireframes during Sprint 3. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#100]
As a developer, I need to update the wireframes to match with what we have released and in order to get a better idea of what the future features we will implement will look like.

**Comment by jaychenblue** [comment]
@SeifElDerby Once the indoor direction implementation is done, any changes in the implementation design should be reflected in the updated wireframes.

**Comment by SeifElDerby** [comment]
The wireframes are update according to the changes in the implementation design made during sprint 3
