### ISSUE TITLE
Center all the building labels so that they appear in the middle of the building outline.

### ISSUE THREAD

**Issue by vincentcerri** [jaychenblue/scout-concordia#107]
All the building labels should be clearly visible within the building outline. Look at "HU" shown in the image below. 

![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/9efc1d79-b0f4-43f4-a84b-1a06006b3993)

**Comment by JenYn** [comment]
**Acceptance criteria:**
- [ ] All buildings have their name centered in within the outline

**Comment by vincentcerri** [comment]
Is this ready to test? which branch were the changes made in?

**Comment by JenYn** [comment]
I see no commits linked to this issue, thus it has not been worked on.

**Comment by jaychenblue** [comment]
@JenYn @vincentcerri Is this UI issue high priority?
