### ISSUE TITLE
BY-19  As a user, I want the default language of the application to be English if my phone is set to any other language than French or English. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#108]
The default language of the application  will be English if the user’s phone is set to a language other than French or English.

**Comment by 13rinda** [comment]
<img width="292" alt="Screen Shot 2020-03-14 at 12 12 03 PM" src="https://user-images.githubusercontent.com/31190776/76685860-4e16e800-65ed-11ea-98b5-46e7665adad0.png">

With the latest commit, if the phone is set to operate in the French language, then the buttons of the application will display in French as illustrated in this screenshot.
