### ISSUE TITLE
BY-8  As a user, I want my preferences to be set locally. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#11]
Preferences are set locally for all users. Settings such as accessibility, language, etc. are all saved locally.

**Comment by JenYn** [comment]
**Implementation strategy:** 

We will follow this documentation in order to learn how to implement local storage: https://developer.android.com/guide/topics/data

**Mockup:** 
There is no mockup for this feature since it is mainly backend. 

**Acceptance criteria:**

- [ ] Settings are successfully stored (in a file)

- [ ] Settings remain when we close and open the app

**Comment by Averynder** [comment]
What are these settings and under what conditions are:
1. all settings are registered into the file
2. settings are loaded into the system
3.  considered something to be saved for future reference?

Please elaborate

**Comment by jaychenblue** [comment]
I believe the only settings being saved are for accessibility purposes and possibly personal preference (e.g. a user may only want to take the elevator to go to their classes).

Settings should be saved locally in whatever format. They should remain saved as long as the user has the application installed. When the user uninstalls the app, the settings will disappear.

Given the time constraints, the menu + settings may be dropped entirely. This is a discussion that the entire team needs to weigh in on, especially when it comes to planning for sprint 4.

@JenYn can provide further details if necessary.

**Comment by Averynder** [comment]
> 
> 
> I believe the only settings being saved are for accessibility purposes and possibly personal preferences (e.g. a user may only want to take the elevator to go to their classes).
> 
> Settings should be saved locally in any format. They should remain saved as long as the user has the application installed.
> 
> Given the time constraints, the menu + settings may be dropped entirely. This is a discussion that the entire team needs to weigh in on, especially when it comes to planning for sprint 4.
> 
> @JenYn can provide further details if necessary.

Again elaborate, what you want saved exactly as this is not specific. Are we saving every possible option for escalators and or elevators, ramps, stairs...etc.? Is it just one option for handicap? The following questions from my previous post remain unanswered:
1. When are the settings registered into the file
2. When are the settings loaded into the system
3. Was asked above, what exactly are we saving (in better terms)

Just saving something into a file is one thing but the concept of settings should be well defined in the acceptance tests because this is open to many interpretations mainly based on design that I am currently unaware of.

**Comment by JenYn** [comment]
Initially we had decided to have preferences that could be saved locally, ie accessibility preferences and language preferences. However, I think language preferences will simply be a state that depends on the toggle and i am wondering if it could be the same thing for accessibility preferences. 
What do you guys think?

**Comment by Averynder** [comment]
> 
> 
> Initially we had decided to have preferences that could be saved locally, ie accessibility preferences and language preferences. However, I think language preferences will simply be a state that depends on the toggle and i am wondering if it could be the same thing for accessibility preferences.
> What do you guys think?

If you want to save this state or load it without having to set it each time you start the app, it needs to be saved somewhere

**Comment by JenYn** [comment]
We will not be needing this anymore considering the fact that no sensitive information will be saved. 
The google calendar will use Google Autentication, and the accessibility settings will be a boolean.

**Comment by jaychenblue** [comment]
@JenYn There still needs to be a way to store/change the wheelchair option. This will probably a button of some kind in the menu or settings.

**Comment by JenYn** [comment]
@jaychenblue Ok, in that case let's push it to Sprint 4

**Comment by JenYn** [comment]
This is related to issue #119. It will allow us to set the wheelchair information for the user for as long as they have the application.

**Comment by JenYn** [comment]
I implemented the menu using PreferenceFragment, which automatically saves settings to SharedPreferences when the user changes them. I tested this to make sure that the settings were indeed saved by closing the app, restarting the emulator, closing the editor and running the program again, and in all cases, the settings were the same as the ones previously set. 

More information can be found here: https://developer.android.com/reference/android/preference/PreferenceFragment
