### ISSUE TITLE
Option to go back to the main map display when the user is on the menu.  

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#115]
The users will be able to access the main map display when they are on the sidebar menu by clicking on “Scout Concordia”

**Comment by JenYn** [comment]
![Mockups Final Final-34](https://user-images.githubusercontent.com/26283932/75617966-7eae4a80-5b34-11ea-9c09-809e78428a9b.png)

**Comment by JenYn** [comment]
Acceptance criteria:

- [ ] If the user clicks on “Scout Concordia”, the main page is displayed

**Comment by jaychenblue** [comment]
Issues #115, #116 and #117 are redundant. They can be combined as one issue. If anything, the entire menu page should be only one issue.

**Comment by JenYn** [comment]
Please refer to issue #119
