### ISSUE TITLE
BY-38 As a user, I want to be able to select from multiple calendars.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#128]
Users will be able to select from multiple Google Calendars they have when they first log in.

This issue is related to issue #34

**Comment by JenYn** [comment]
The implementation will look like this:

![image](https://user-images.githubusercontent.com/26283932/75631959-69cdc780-5bc5-11ea-8f55-ee4d5dec5590.png)

**Comment by JenYn** [comment]
Acceptance criteria:
- [ ] When the user logs in to their Google Account, they will be prompted to select the calendar they which to import if they have more than one.

Note: The calendar will not yet be displayed because it has not yet been implemented.

**Comment by ManpreetSohal** [comment]
Implementation details:

 - Once the user is signed in and permission to access calendar is granted, Google's Calendar API is used to initialize a Calendar service with a valid access token.
- Using the Calendar service a CalendarList object is retrieved.
- A single selection dialog is created with all of the user's calendars as options (The dialog 
 cannot be cancelled).
- After user makes a selection and presses Select button, the Calendar service is used to fetch 
 details of the calendar such as events and more. The selected calendar is fetched by providing it's id to the get() method of the service.

* If user presses cancel on the dialog, user is redirected to the MapsActivity.
