### ISSUE TITLE
Dynamically change Shuttle Schedule strings according to System Language

### ISSUE THREAD

**Issue by vicmanea** [jaychenblue/scout-concordia#133]
Users will have an adaptive language option on the Shuttle Schedule which stays in tune with the default System Language setting.

**Comment by vicmanea** [comment]
Acceptance criteria:

- [ ] : The Shuttle Schedule text is adaptive to system settings

**Comment by JenYn** [comment]
This is a duplicate of issue #18. We will therefore close it.
