### ISSUE TITLE
In Shuttle Schedule, fix inconsistencies

### ISSUE THREAD

**Issue by vicmanea** [jaychenblue/scout-concordia#135]
Users will have a more consistent and clear design to the Shuttle Schedule. (We want to remove blue filter overlay on the page, center the text, and increase the font size.)

**Comment by vicmanea** [comment]
Acceptance criteria:

- [ ] : The Shuttle Schedule page looks clean and concise

**Comment by JenYn** [comment]
The readability should be similar to this mockup:

**Comment by JenYn** [comment]
The layout now looks like this. The colours of the row alternate in order to make it easier to read. 
![image](https://user-images.githubusercontent.com/26283932/76691899-2ee87c80-6626-11ea-991a-70c7e5b63617.png)

**Comment by jaychenblue** [comment]
Very nice. The colors are much better now.

**Comment by vicmanea** [comment]
Outstanding. Makes a big difference from before.

**Comment by jaychenblue** [comment]
As mentioned in the pull request, I think centering everything in the columns would look even better.
