### ISSUE TITLE
Dynamically change Building Info strings according to System Language

### ISSUE THREAD

**Issue by vicmanea** [jaychenblue/scout-concordia#136]
Users will have an adaptive language option on the Building Info, which stays in tune with the default System Language setting.

**Comment by vicmanea** [comment]
Acceptance criteria:

- [ ] : The Building Info text is adaptive to system settings

**Comment by jaychenblue** [comment]
I'm not quite sure what the purpose of this issue is. Can you elaborate?

**Comment by vicmanea** [comment]
This was originally an extension of the language-switching feature, as I figured that every person would be in charge of implementing it into their own component.

**Comment by JenYn** [comment]
This is a duplicate of issue #18. We will therefore close it.
