### ISSUE TITLE
change top bar color from green to our theme color red as TA requested 

### ISSUE THREAD

**Issue by JYSW380** [jaychenblue/scout-concordia#148]
the colour must be #74091F (primaryColor) in colors.xml
![Screen Shot 2020-03-09 at 8.36.25 PM.png](https://images.zenhubusercontent.com/5e25e39a5e668415ca31f2cb/ae80bb85-e5a0-4869-8732-2505d1765b37)

**Comment by JenYn** [comment]
Acceptance criteria:
- [x] Colour of top bar must correspond to the app's primary colour (#74091F)

**Comment by JenYn** [comment]
![image](https://user-images.githubusercontent.com/26283932/76691509-bb447080-6621-11ea-82d7-c63ae158f1d5.png)

**Comment by jaychenblue** [comment]
Nice. Open a pull request when you're ready.

**Comment by JenYn** [comment]
Implementation details: in styles.xml, had to change the colour of item called "colorPrimaryDark".
