### ISSUE TITLE
Buttons are not appropriately placed in the UI

### ISSUE THREAD

**Issue by jaychenblue** [jaychenblue/scout-concordia#152]
**ID**:
**Name**: Buttons are appropriately placed in the UI
**Related to issue**: BY-14 (#15)
**Reported by**: Jay
**Submitted**: March 10
## **Environment**
**Device**: Nexus 5X
**API Version**: API 29 x86
## **Details**
**Summary**: The two buttons (Get Directions and Explore Inside) are not appropriately placed in the UI
**Steps to reproduce**:

1. Navigate to the SGW (or Loyola) campus
2. Click on any building

**Expected results**: The buttons should be inside the pop up box that includes the building info
**Actual results**: The buttons are outside the building info pop up box

![Screen Shot 2020-03-10 at 5.51.54 PM.png](https://images.zenhubusercontent.com/5c5c699dfb3a13446559cbbd/8da7b13e-f11d-4c0e-b2f7-7db76775865c)

## **Severity**
**Severity**: Medium
**Priority**: Low

**Comment by JenYn** [comment]
**ID**:
**Name**:
**Related to issue**:
**Reported by**:
**Submitted**:
## **Environment**
**Device**:
**API Version**:
## **Details**
**Summary**:
**Steps to reproduce**:
**Expected results**:
**Actual results**:
## **Severity**
**Severity**:
**Priority**:

**Comment by vincentcerri** [comment]
Please change this from a Bug to a product enhancement. The buttons were placed there temporarily as we did not want them to be overlapped with the search bar. 

Also after doing research, it is impossible to place the buttons in the info window as that is a static image. The buttons will be displayed at the bottom of the screen in a small box.

**Comment by jaychenblue** [comment]
> Please change this from a Bug to a product enhancement. The buttons were placed there temporarily as we did not want them to be overlapped with the search bar.
> 
> Also after doing research, it is impossible to place the buttons in the info window as that is a static image. The buttons will be displayed at the bottom of the screen in a small box.

OK, I changed it to a product enhancement. Will the buttons in a small box still be separate from the info window? I'm bringing this up because I remember the product owner didn't approve the feature because of the "misplaced" buttons. One possible option is to update the mockup corresponding to this feature so that it reflects the implemented design.

**Comment by vincentcerri** [comment]
Yes I think we will have to update the mockups to reflect these changes.

**Comment by vincentcerri** [comment]
update: 
![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/96f1af58-bdc7-41a9-b2d0-9ccb18f1388f)

![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/8f2aefdb-2459-49ed-893c-37882496716f)

These changes have been commited.
