### ISSUE TITLE
BY-24 As a user, I want to receive an estimate of time it would take to get the next bus shuttle and travel to another campus

### ISSUE THREAD

**Issue by vicmanea** [jaychenblue/scout-concordia#156]

**Comment by vicmanea** [comment]
Acceptance criteria:

- [ ]  The application successfully pulls the current day and time

- [ ]  The application finds the next shuttle time depending on the time and location

- [ ] The application builds an estimate of time by factoring in the route time estimate as long as the time left until the next shuttle bus comes

**Comment by jaychenblue** [comment]
@vicmanea You forgot to link your commits to this issue. In the future, remember to add the GitHub issue number to your commit messages. Here's an example:

"[#156] Add method to do something"

Also, check off the acceptance criteria if they're satisfied.

**Comment by JenYn** [comment]
We will reopen this issue because the backend is complete, however it is not displayed to the user yet.

**Comment by jaychenblue** [comment]
The acceptance criteria can only be considered complete when these estimates are visually shown in the application. Once the feature is fully complete, this issue can be closed.

**Comment by jaychenblue** [comment]
@vicmanea @JYSW380 Is this issue related to #218?

**Comment by vicmanea** [comment]
> @vicmanea @JYSW380 Is this issue related to #218?

Yes it is!
