### ISSUE TITLE
Refactor unit tests and upgrade JUnit version

### ISSUE THREAD

**Issue by jaychenblue** [jaychenblue/scout-concordia#166]
Some issues that should be investigated:

- Ordering of unit tests
- Atomic unit tests
- Upgrade JUnit to JUnit 5

Test classes affected:

- LinkedListTest
- BuildingInfoTest

**Problems and discussion:**

_Ordering of unit tests_

This is still unclear. Further research is needed.

UPDATE: This was resolved (see comment).

_Atomic unit tests_

There are setup and teardown functions that run before and after every test. They are using the @Before and @After annotations and involve setting up objects and setting them to null for every test. I believe that all the unit tests are atomic, but @Averynder can provide further discussion.

UPDATE: This was resolved (see comment).

_Upgrade JUnit to JUnit 5_

Apparently there was a wrong import that used an older version of JUnit. For this project, we are using JUnit 5 so the appropriate version should always be used for unit tests.

Requirements

- Issue https://github.com/jaychenblue/scout-concordia/issues/145 should be completed

Acceptance Tests

- [x] All tests should pass
- [x] Ordering should work
- [x] JUnit 5 should be the current version

Accomplishments

- Refactors the unit tests

**Comment by jaychenblue** [comment]
When transitioning to JUnit 5, the @Before / @After annotations were changed to @BeforeAll / @AfterAll. However, the new annotations didn't reflect the original intention. As a result, the @BeforeEach / @AfterEach annotations were used.

@BeforeAll / @AfterAll run once before and after the entire test class. @BeforeEach / @AfterEach run once before and after _every test_.

With proper set up and teardown functions in place, ordering is no longer needed because every test is self-contained and atomic. This also resolves the issue of atomic unit tests. They all pass individually and when run together as a suite.

**Comment by Averynder** [comment]
Runs well just as anticipated. One of the reasons to upgrade to Junit 5 was to avoid potentially mishaps with old annotations. Guess all you needed to do was "test" the code
