### ISSUE TITLE
D-# Bug when trying to display a calendar with events with no start and end dates (reminders)

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#167]
**ID**: x
**Name**: Bug when trying to display a calendar with events with no start and end dates (reminders)
**Related to issue**: #7, #34 , #130, related to pull request #165 
**Reported by**: Jennifer Younanian
**Submitted**: 15/03/2020
## **Environment** 
**Device**: Pixel 3
**API Version**: 28
## **Details**
**Summary**: when trying to open a calendar, if it has events with no start and end dates, for example, reminders. 
**Steps to reproduce**:
1. Sign in to google account
2. Select a calendar with reminders or whole day events
(will attach pictures in comments below)
**Expected results**:
Reminders and tasks are not displayed and a message is displayed notifying the user of the fact that reminders are not displayed. 
**Actual results**:
Application crashes. 
## **Severity**
**Severity**: High
**Priority**: High

**Comment by JenYn** [comment]
For example, I have a separate calendar for all due dates where I create daily events in order to overlay them with my general calendar. However, when I try opening it on the app, it crashes or goes back to the map page.
![image](https://user-images.githubusercontent.com/26283932/76707692-c8b43600-66c7-11ea-8512-d8f73efd0524.png)
![image](https://user-images.githubusercontent.com/26283932/76707700-d8337f00-66c7-11ea-818f-b2163776f0ca.png)

**Comment by JenYn** [comment]
however, when trying to select another calendar with actual events, nothing is displayed.
![image](https://user-images.githubusercontent.com/26283932/76707780-9d7e1680-66c8-11ea-9fbd-b13003689c8b.png)
![image](https://user-images.githubusercontent.com/26283932/76707782-a1aa3400-66c8-11ea-90ff-944b0e48ef65.png)

**Comment by JenYn** [comment]
After adding a location to the event, it was displayed:
![image](https://user-images.githubusercontent.com/26283932/76707951-a7544980-66c9-11ea-8d9c-37476b9bc7fb.png)

However, we cannot see the name of the event and we cannot scroll

**Comment by ManpreetSohal** [comment]
The bug was not caused by events with no start/end date (all day events) as those events are simply not displayed. The bug was caused trying to set the location or title on an event on the schedule when they were null.

**Comment by ManpreetSohal** [comment]
Implementation details:

try catch block to catch exceptions and set the missing information to null. For example, when trying to fetch title or location on an event that does not have them set, they are set to null.
