### ISSUE TITLE
D-# Location name stretches out calendar event

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#168]
**ID**: X
**Name**: location name stretches out calendar event 
**Related to issue**: #165
**Reported by**: Jennifer Younanian
**Submitted**: 15/03/2020
## **Environment**
**Device**: Nexus 3
**API Version**: 28
## **Details**
**Summary**: 
When opening a calendar with an event with a long location name, the name of the location stretches out the block. 
**Steps to reproduce**:
1. Launch app
2. Click on calendar tab
3. Select a calendar with an event with a long name (for example Pavillion Henry F.Hall Building, Édifice Henry F. Hall, Boulevard de Maisonneuve O, Montréal, QC H3G 1M8, Canada)
**Expected results**:
Calendar event wraps around/compresses the name as to not stretch out the event block
**Actual results**:
Calendar event is stretched out by the name of the location
## **Severity**
**Severity**: High
**Priority**:High

![image.png](https://images.zenhubusercontent.com/5e2890605e668415cad95c6b/e6136169-92c6-45e2-b7e1-01bd001d9d59)

**Comment by ManpreetSohal** [comment]
Implementation details:

If title or location name is longer than 15 characters, display only the first 15 characters. Full information is displayed on the dialog asking whether user would like directions to the location.
