### ISSUE TITLE
D-# Recurring events are not displayed 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#173]
**ID**: X
**Name**: Recurring events are not displayed
**Related to issue**: #130
**Reported by**: Jennifer Younanian
**Submitted**: 20/03/2020
## **Environment**
**Device**: Pixel 3
**API Version**: 28
## **Details**
**Summary**: 
When displaying a calendar, the events do not show up. 
**Steps to reproduce**:
1. Launch the application 
2. Open a calendar with events on it
3. Display the calendar

**Expected results**:
The events are supposed to be displayed on the app as they are displayed on the google calendar.
**Actual results**:
The events are not displayed on the app. This only happens for some calendars, however. 
## **Severity**
**Severity**: High 
**Priority**: High

**Comment by JenYn** [comment]
When I select my calendar called "Jen", we do not see the events. The events to this calendar were added in January when I first finalized my schedule. 
![image](https://user-images.githubusercontent.com/26283932/77212748-baf31c00-6ade-11ea-86d4-6790036ad5da.png)

**Comment by JenYn** [comment]
I created a new event on the same calendar called "TEST FOR BUG", and we now see it on the app:
![image](https://user-images.githubusercontent.com/26283932/77212795-ed9d1480-6ade-11ea-8dde-9a8432b3ff9e.png)

**Comment by JenYn** [comment]
### CAUSE OF THE BUG:
The events that I created in January were recurrent events:
![image](https://user-images.githubusercontent.com/26283932/77213009-aebb8e80-6adf-11ea-8285-549eab53fc4c.png)

**Comment by ManpreetSohal** [comment]
On it.

**Comment by JenYn** [comment]
Acceptance criteria:
- [x] We can see events that  were created to be recurring

**Comment by JenYn** [comment]
We can now see the events that I had created in January 


![image](https://user-images.githubusercontent.com/26283932/77216155-c9493400-6aee-11ea-83e4-1728fc3e78d4.png)
![image](https://user-images.githubusercontent.com/26283932/77216171-e978f300-6aee-11ea-896c-4b471e4c9063.png)

![image](https://user-images.githubusercontent.com/26283932/77216185-f1389780-6aee-11ea-8a42-0e5f4315a4ed.png)
