### ISSUE TITLE
BY-24 Refactor the shuttle times into external txt files

### ISSUE THREAD

**Issue by vicmanea** [jaychenblue/scout-concordia#180]
Currently the times are hardcoded into the shuttleInfo class, which is poor coding practice. The intent is to move the shuttle times from the array to external text files, subsequently encrypt them and retrieve them whenever they are needed by the relevant class.

Acceptance Criteria:

- [x] The shuttle time files are present as external resources.

- [x] The class successfully retrieves the files and reads them.

- [x] The class can do accurate calculations using the times in the files.

**Comment by vicmanea** [comment]
<img width="822" alt="Screen Shot 2020-03-25 at 4 18 56 PM" src="https://user-images.githubusercontent.com/36647329/77581583-56580880-6eb4-11ea-8148-258dc8661c84.png">

<img width="1119" alt="Screen Shot 2020-03-25 at 4 19 18 PM" src="https://user-images.githubusercontent.com/36647329/77581610-6374f780-6eb4-11ea-86d0-645fc2062991.png">

The ShuttleInfo class now successfully pulls the times from external resource files, using its calling class' context, and does the required logic calculations.

**Comment by vincentcerri** [comment]
@vicmanea  is this complete?

**Comment by vicmanea** [comment]
> @vicmanea is this complete?

Yes this is complete, as far as functionality is concerned.

**Comment by jaychenblue** [comment]
@vicmanea I believe you said you had some sample code for testing/playing around with the ShuttleInfo class. Is this in the code somewhere or did you delete it?

There is further refactoring that can be done. The functions (getEstimatedRouteTimeFromSGW, getEstimatedRouteTimeFromLoyola) are too long and should be refactored.

I noticed that all the methods have two different versions: one for SGW and one for Loyola. A possible improvement would be to have SGW and Loyola simply be function parameters (Integer or Boolean) that would change the function's behaviour accordingly. Having two separate versions results in a lot of repeated code.

These changes shouldn't take long. However, let me know if you can address them this sprint or in sprint 4.

**Comment by vicmanea** [comment]
> @vicmanea I believe you said you had some sample code for testing/playing around with the ShuttleInfo class. Is this in the code somewhere or did you delete it?
> 
> There is further refactoring that can be done. The functions (getEstimatedRouteTimeFromSGW, getEstimatedRouteTimeFromLoyola) are too long and should be refactored.
> 
> I noticed that all the methods have two different versions: one for SGW and one for Loyola. A possible improvement would be to have SGW and Loyola simply be function parameters (Integer or Boolean) that would change the function's behaviour accordingly. Having two separate versions results in a lot of repeated code.
> 
> These changes shouldn't take long. However, let me know if you can address them this sprint or in sprint 4.

Yes, I do agree that this can be further refactored. However the methods were split into two separate methods for simplicity and to minimize the chances of other devs getting errors. The philosophy behind this is that one method returns one relevant output depending on relevant factors, and that is it. I wanted to avoid other developers having to go through a learning curve with this Class, hence I limited the options and, consequently, the potential for mistakes.

**Comment by jaychenblue** [comment]
@vicmanea @Averynder Can this issue be closed?
