### ISSUE TITLE
AT-13 As a user, I want to be able to find the fastest path from one building to another. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#196]
Related to issue #21 
User Story BY-21

This pertains to requirement 2.)c
“Show direction on the map (using Google API)”

**Comment by JenYn** [comment]
### Acceptance test:
| Test case ID | AT- |
| --- | --- |
| User Story | BY-21 As a user, I want to be able to find the shortest path from one building to another.  |
| Acceptance Criteria | -[ ] First <br/> -[ ] Second|

**Comment by JYSW380** [comment]
when searching for directions, we have a drop down list shown all Concordia buildings
<img width="252" alt="Screen Shot 2020-03-29 at 6 46 41 PM" src="https://user-images.githubusercontent.com/41170611/77863094-cdabd600-71ed-11ea-8c88-d246267ba221.png">
path clearly show between buildings in the different campus
<img width="278" alt="Screen Shot 2020-03-29 at 6 46 04 PM" src="https://user-images.githubusercontent.com/41170611/77863074-b66ce880-71ed-11ea-8cba-8c6520f49df9.png">
path clearly show between buildings on the same campus
<img width="268" alt="Screen Shot 2020-03-29 at 6 46 21 PM" src="https://user-images.githubusercontent.com/41170611/77863075-ba990600-71ed-11ea-8507-428cc4c9a07e.png">
i am able to select the walking/car/public transit/shuttle bus mode of transport(out shuttle use the same route as transit)
<img width="252" alt="Screen Shot 2020-03-29 at 6 46 41 PM" src="https://user-images.githubusercontent.com/41170611/77863081-bec52380-71ed-11ea-8996-8c48dd3a4260.png">

**Comment by mkshiblu** [comment]
ACCEPTED
