### ISSUE TITLE
AT-22  As a user, I want to find the shortest path from one class to another which are in different buildings.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#197]
Related to issue #22 
User Story : BY-22

This pertains to requirement 4.) f
“Indoor directions from SGW to Loyola and vice versa (or from Building to Building in the same campus)”

It is important to note that we are displaying the shorted path based on Google API. 
Displaying path options will have to be a different user story.

**Comment by JenYn** [comment]
### Acceptance tests:
- [ ] When searching for directions, the path is clearly shown from one class to another which are in different buildings. 
- [ ] Path is displayed between classes on the same campus
- [ ] Path is displayed between classes in different campuses
- [ ] Path is displayed when Walking is selected as mode of transport
- [ ] Path is displayed when Car is selected as mode of transport
- [ ] Path is displayed when Public Transit is selected as mode of transport
- [ ] Path is displayed when Shuttle bus is selected as mode of transport

**Comment by mkshiblu** [comment]
ACCEPTED
