### ISSUE TITLE
AT-15  As a student with accessibility issues, I want to find the shortest path from point A to point B which take into account my preferences. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#198]
Related to issue #23 
Related to user story BY-23

This takes into account the user's preferences and leads them to take the elevator if they have accessibility preferences turned on.

Pertains to requirement 4.) c
“Show directions for students with disabilities”

**Comment by JenYn** [comment]
### Acceptances tests:
- [ ] When searching for directions, the user is told to take the elevator.

**Comment by mkshiblu** [comment]
How can I test this feature? Where should I set that I need to use the elevators with wheelchair access?

**Comment by JenYn** [comment]
> How can I test this feature? Where should I set that I need to use the elevators with wheelchair access?

We should not have created this acceptance test as it is currently only implemented in the backend and we do not have the UI for it. However, this will be ready in Sprint 4. 
Sorry about that.

**Comment by JenYn** [comment]
How to test this:
- Open the settings page
- Turn on accessibility
- Search H-903 to H-802
You will see the user is shown a path taking the elevators.

**Comment by mkshiblu** [comment]
It does not show anything after hitting the direction button in the Modal

![image](https://user-images.githubusercontent.com/15908043/80018483-116bc580-84a4-11ea-91aa-0070369b3b42.png)

![image](https://user-images.githubusercontent.com/15908043/80018541-26e0ef80-84a4-11ea-9863-4e1994c64e2b.png)

![image](https://user-images.githubusercontent.com/15908043/80018591-395b2900-84a4-11ea-8c35-c26f277c4f68.png)

![image](https://user-images.githubusercontent.com/15908043/80018607-41b36400-84a4-11ea-9be1-f116a5da1e3f.png)

![image](https://user-images.githubusercontent.com/15908043/80018660-5859bb00-84a4-11ea-8e95-7ffb318a1108.png)
