### ISSUE TITLE
AT-16  As a user, I want to be able to switch between modes of travel.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#199]
Related to issue #25 
Related to BY-25

Pertains to requirement 2.)e
“Support multiple transportation ways (Walk, car, public transportation)”

Pertains to requirement 2.)f
“Support for the concordia shuttle service time-aware and location aware.”

**Comment by JenYn** [comment]
### Acceptance tests
- [ ] When searching for directions, a display pops up giving us the option of choosing between walking, taking the bus, driving, or taking the shuttle.

**Comment by JYSW380** [comment]
i am able to select between walking,taking the bus, driving, or taking the shuttle.(our shuttle use transit that provided by google api )
<img width="252" alt="Screen Shot 2020-03-29 at 6 46 41 PM" src="https://user-images.githubusercontent.com/41170611/77863371-dbfaf180-71ef-11ea-9209-590a5d9e6200.png">

**Comment by mkshiblu** [comment]
ACCEPTED
