### ISSUE TITLE
AT-17  As a user, I want to be able to see the floor plans of the building.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#200]
Related to issue #28 
User Story BY-28

Pertains to requirement 4.) a
“Be able to locate rooms (start or destination points) in the indoor map for specific floor”

**Comment by JenYn** [comment]
### Acceptance Tests:
- [ ] Floor plans are displayed when we click on a building's outline and then click on "Go Inside" 
- [ ] Floor plans display room numbers
- [ ] Floor plans highlight washrooms, escalators, and elevators

Note: Only floors to which the plans were provided will be displayed.

**Comment by JYSW380** [comment]
after click on H building --> explore Inside, i am able to see the 1st, 8th and 9th floor plans, so far we have implemented on H building and CC building.
<img width="267" alt="Screen Shot 2020-03-29 at 6 38 53 PM" src="https://user-images.githubusercontent.com/41170611/77862926-9688f500-71ec-11ea-9baa-7e03904dfa43.png">

<img width="275" alt="Screen Shot 2020-03-29 at 6 39 04 PM" src="https://user-images.githubusercontent.com/41170611/77862928-97ba2200-71ec-11ea-9331-a03f6c7fbe95.png">

**Comment by mkshiblu** [comment]
Accepted, Rendering needs to be optimized if possible, it takes some time to re-render on changing floors
