### ISSUE TITLE
AT-19  As a student, I want the target room I want to go to to be clearly marked.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#201]
Related to issue #74 
User Story BY-31

Pertains to requirement 4.) a
“Be able to locate rooms (start or destination points) in the indoor maps for a specific floor”

**Comment by JenYn** [comment]
### Acceptance tests
- [ ] The target room is marked clearly when we search for it

**Comment by mkshiblu** [comment]
ACCEPTED
