### ISSUE TITLE
AT-20  As a student, I want to be able to scroll access different floors of the building

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#202]
Related to issue #75 
User Story BY-32

Pertains to requirement 4.)a
“Be able to locate rooms (start or destination points) in the indoor maps for a specific floor”

**Comment by JenYn** [comment]
### Acceptance tests
- [ ] When inside a building, we can access different floors

**Comment by JYSW380** [comment]
i am able to see different floor map(so far we have implemented 1st, 8th and 9th floor)
<img width="274" alt="Screen Shot 2020-03-29 at 7 30 24 PM" src="https://user-images.githubusercontent.com/41170611/77863904-c1c31280-71f3-11ea-8429-a1b36e58c1f7.png">

**Comment by mkshiblu** [comment]
ACCEPTED
