### ISSUE TITLE
AT-06  As a user I want to view my calendar on the app.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#203]
Related to issue #130 
BY-100

Pertains to requirements 3.) a
“Connect to Google Calendar”

**Comment by JenYn** [comment]
### Acceptance tests
- [ ] As a user, I am able to sign into my Google Account when I click on the calendar tab and have never signed in before
- [ ] As a user I am able to select from multiple calendars
- [ ] As a user, I am able to see my calendar displayed on the app

**Comment by JYSW380** [comment]
every first time open the app, i am able to sign into my google account and later can select my google account to import my calendars
<img width="280" alt="Screen Shot 2020-03-29 at 7 25 09 PM" src="https://user-images.githubusercontent.com/41170611/77863831-49f4e800-71f3-11ea-840f-d47666d0e07b.png">
my calendar are able to show on app and i can scroll down to see more information
<img width="274" alt="Screen Shot 2020-03-29 at 7 26 04 PM" src="https://user-images.githubusercontent.com/41170611/77863835-4c574200-71f3-11ea-8f7d-8b5089fde8f6.png">
<img width="276" alt="Screen Shot 2020-03-29 at 7 26 13 PM" src="https://user-images.githubusercontent.com/41170611/77863837-4d886f00-71f3-11ea-8bd4-51e242e6d6a4.png">

**Comment by mkshiblu** [comment]
ACCEPTED. However, if there is only one calendar, the user should not be prompted and that calendar should be chosen by default.
