### ISSUE TITLE
AT-18 As a user, I want interior directions for the shortest path from point A to point B.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#205]
Related to issue #29 
User Story BY-29

Pertains to requirement 4.) b
“Show shortest path directions”

Pertains to requirement 4.) e
“Be able to show directions between rooms in different floors”

**Comment by JenYn** [comment]
### Acceptance tests
- [ ] When searching for directions, the path is clearly shown from one class to another
- [ ] When searching for directions between two classes on a different floors, the path is clearly shown

**Comment by mkshiblu** [comment]
ACCEPTED.  You should've mentioned the steps to test a feature like this. It took a while to find the building with floor plan
