### ISSUE TITLE
BY-45 As a student, I want written directions to be displayed when I select a destination.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#206]
Users will be able to see written instructions to follow in order to reach their destination. This applies to both indoor and outdoor directions. Note that there will be no directions displayed for the shuttle bus or the public transit modes of transport.

**Comment by JenYn** [comment]
Acceptance criteria:
- [ ] No directions displayed when public transit is selected as a mode of transport
- [ ] No directions displayed when shuttle is selected as mode of transport
- [ ] Written directions are displayed when walking is selected
- [ ] Written directions are displayed when Car is selected

**Comment by jaychenblue** [comment]
Waiting for the product owner's input.

**Comment by jaychenblue** [comment]
@JenYn Is there a mockup corresponding to this issue? If so, please attach it to this page.

I understand that we're waiting for the product owner's input on whether this feature should be implemented. When you receive an update, please post it here.

**Comment by jaychenblue** [comment]
According to @JenYn, this will not be done.
