### ISSUE TITLE
BY-21  As a user, I want to be able to get directions from one building to another. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#21]
User selects a starting building, a destination building, and mode of travel. Directions are displayed on the map using Google API,

**Comment by JenYn** [comment]
**implementation strategy:**
We will have to do more research about how to implement this feature. 
There are however a lot of resources online such as this one: https://developers.google.com/maps/documentation/javascript/directions

**Acceptance criteria:**
- [ ] Different paths suggested with the ETA
- [ ] Selecting the shortest path option displays the path on the map

**Comment by JenYn** [comment]
![Mockups Final Final-06](https://user-images.githubusercontent.com/26283932/75618573-765b0d00-5b3e-11ea-95f5-bbd90ce2098f.png)

**Comment by jaychenblue** [comment]
I believe multiple paths may be beyond the scope of this project. @JenYn and @JYSW380 can weigh in if needed.

**Comment by JYSW380** [comment]
@jaychenblue i agree with showing multiple paths is beyond the scope of this project, instead will only show the shortest path on map.
@JenYn please let me know what do you think?

**Comment by ManpreetSohal** [comment]
@JenYn and I discussed the issue and I have edited it from "displaying multiple paths from which the user can choose the shortest" to simply displaying a path to the destination using Google API as mentioned in the requirements for feature 2.
