### ISSUE TITLE
Automated system tests for sprint 4

### ISSUE THREAD

**Issue by jaychenblue** [jaychenblue/scout-concordia#217]
**System tests to do:**

- [x] Selecting modes of transportation
- [x] Get directions from current location
- [x] Get outdoor directions
- [x] Get indoor directions
- [x] Open the menu and accessing different pages

**Acceptance criteria:**

- [x] All tests should pass when run individually
- [x] All tests should pass when run together as a suite

**Comment by ManpreetSohal** [comment]
The tests pass but one thing that needs to be looked into is when a test is first run it fails as the program is unable to find the view resources, but when the same test is run again it passes without any problems.

**Comment by jaychenblue** [comment]
> The tests pass but one thing that needs to be looked into is when a test is first run it fails as the program is unable to find the view resources, but when the same test is run again it passes without any problems.

After running the tests, I can confirm that only the very first test that accesses the view resources fails. Subsequently, the rest of the tests all pass successfully, including the original one that failed.
