### ISSUE TITLE
BY-22  As a user, I want to find the shortest path from one class to another which are in different buildings.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#22]
Multiple paths are displayed and the user can choose the one they want. Shortest path is displayed when a user inputs a classroom that is in a different building than the class inputted as a destination.

Related to search bar issue #58

**Comment by JenYn** [comment]
**implementation strategy:**
We will have to do more research about how to implement this feature. 
There are however a lot of resources online such as this one: https://developers.google.com/maps/documentation/javascript/directions

**Acceptance criteria:**
- [ ] Different paths suggested with the ETA
- [ ] Selecting the shortest path option displays the path on the map

**Comment by jaychenblue** [comment]
@vincentcerri @JenYn I believe we decided to only display one path. If this is the case, this issue and the acceptance criteria need to be updated.

**Comment by vincentcerri** [comment]
**update:**
This is now working. After some refactoring we will be ready to close.

example: searching from CC-201 -> H-903

![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/e2ef62e5-2980-4909-b038-8af8db958ee1)
![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/a82f81cd-ba50-4b7a-b475-d2e13f967386)
![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/8c4cc589-7246-4000-afe2-be01f587bf06)
![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/26b3ebbb-57dc-4b8f-a1d7-bd61ef0c7349)
![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/91cafaab-5f73-4e1c-b736-4230863a82ec)
