### ISSUE TITLE
BY-32 As a user, I want to be able to see floor map overlays scroll through the floors of the building.

### ISSUE THREAD

**Issue by vicmanea** [jaychenblue/scout-concordia#226]
Acceptance criteria:

- [x] The user can click on a floor button and the relevant floor map appears.
- [x] The user can click away and the floor buttons disappear.
- [x] Only the specific buttons for a specific building will appear when clicking "Explore Inside"

**Comment by jaychenblue** [comment]
@vicmanea @vincentcerri It looks like all the acceptance criteria have been checked off. Is this issue done?
