### ISSUE TITLE
AT-03 As a user, I want additional information about each building.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#228]
Related to issue #15 
Related to User Story BY-14 

This pertains to requirement 1.) e
“Show additional information for each building (pop-up information).

**Comment by JenYn** [comment]
1. Building label shown on the outline of the building.
2. Menu that appears when the building is clicked.
3. In the menu there should be:
a. Name of the building.
b.An “Explore inside” button.
c. A “Get there” button

**Comment by mkshiblu** [comment]
ACCEPTED
