### ISSUE TITLE
AT-04 As a student, I want to be able to access Concordia’s shuttle bus schedule.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#229]
Related to issue #24 
Related to User Story BY-24

Pertains to requirement 2.) f
“Support the Concordia Shuttle Service”

**Comment by JenYn** [comment]
1. A functional shuttle bus button that brings the user to the new page.
2. An up-to-date shuttle schedule that covers all departures from both Loyola and SGW campus.
3. An adaptive scrolling view that covers the entire schedule, which would allow phones of different screen sizes to view the content

**Comment by JenYn** [comment]
Had already been accepted
![image](https://user-images.githubusercontent.com/26283932/79752810-dcfcdb80-82e2-11ea-880f-5d53a6f7fb96.png)

**Comment by mkshiblu** [comment]
ACCEPTED
