### ISSUE TITLE
AT-07 As a user I want to be able to select from multiple calendars. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#231]
Related to issue #128 
Related to user story BY-38

Pertains to requirement 3.)b
“Be able to select among multiple calendars”

**Comment by JenYn** [comment]
- [ ] When the user logs in to their Google account, they will be prompted to select the calendar they wish to import if they have more than one.

**Comment by JenYn** [comment]
Pertains to requirement 3.)b
“Be able to select among multiple calendars”

**Comment by mkshiblu** [comment]
ACCEPTED
