### ISSUE TITLE
BY-24 As a student, I want to be able to access Concordia’s shuttle bus schedule.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#24]
Users will be able to access the Concordia University shuttle bus schedule directly from the app instead of having to navigate away from it.

**Comment by JenYn** [comment]
@vicmanea  you need to talk to whoever is working on the navigation pane.
- once that is done, you need to check the nagivation pane activity to see where to write your code

**Comment by vicmanea** [comment]
![mockup shuttle schedule.png](https://images.zenhubusercontent.com/5e482103a6da94b0ef34431c/9a8c28de-eba8-44d8-b137-21f17b39de53)

The shuttle schedule should look similar to this.

**Comment by vicmanea** [comment]
Here is the checklist of features that should be included for this issue to be considered completed:

- [ ] A functional Shuttle Bus button that brings the user to the new page.

- [ ] An up-to-date shuttle schedule that covers all departures from both the Loyola and SGW campus.

- [ ] An adaptive scrolling view that covers the entire schedule, which would allow phones of different screen sizes to view the content.

**Comment by vicmanea** [comment]
Implementation details:

The main page of the application shows 3 buttons at the bottom. Each of these buttons will start a new "activity" within Android Studio. The Shuttle Bus schedule is its own activity. Once the button is pressed, the application starts the activity which brings the user to a new page. This new page was implemented as an "empty" activity that is linked to the "Shuttle Bus" button. This empty activity is then filled in with a fully-designed and custom-made table which shows the exact departure times depending on campus and time of the week.

**Comment by jaychenblue** [comment]
There shouldn't be three buttons at the bottom. There's supposed to a navigation pane on the bottom (Manu's branch).

As of right now, the shuttle schedule tables don't look like the mockups. The implementation of the design should match the mockups.

**Comment by vicmanea** [comment]
The new "shuttle-schedule-v2" branch addresses these concerns.

**Comment by jaychenblue** [comment]
Why was this issue closed without opening a pull request and merging to master? Reopened.
