### ISSUE TITLE
Allow the user to set their accessibility settings through the settings page

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#241]
This is related to issue #23

This connects the frontend with the back end.
Users will be allowed to set their accessibility preferences by simply clicking on a switch. 

![image.png](https://images.zenhubusercontent.com/5e2890605e668415cad95c6b/d314c5a6-cb02-4a7d-bde7-ebd74124587a)

Currently, clicking on the switch does not do anything. It was implemented at the same time as the menu.

**Comment by JenYn** [comment]
**Acceptance criteria:** 
- [ ] User can access the settings page and set their accessibility preferences 
- [ ] Path displayed makes the user take the elevator when the switch is turned on
- [ ] Path displayed makes the user take the escalator when the switch is not turned on

**Comment by jaychenblue** [comment]
I think this issue is redundant with #11. You can simply add more details to the existing issue and close this one.

**Comment by JenYn** [comment]
I reopened it because issue #11 was not needed anymore, since by implementing the menu with Settings Fragment, there's automatically a Shared Preferences. I explained it there and closed the issue. I'll link the commits associated with linking the backend with the front end to this issue.
