### ISSUE TITLE
BY-25  As a user, I want to be able to switch between modes of travel.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#25]
Users will be able to select the model of travel (walking, car, shuttle, public transportation) and directions based on their choice will be displayed.

Related to #26

**Comment by JenYn** [comment]
@JYSW380 you need to speak with Jay to make sure he's done outdoor directions

**Comment by vincentcerri** [comment]
The final design should resemble this mockup: 
![get directions mockup.PNG](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/2b54297e-9511-4ec3-a33b-e271d7577f95)

Here is the checklist of features that should be included for this issue to be considered completed:
- [ ] map overlay to allow the user to switch between public transportation, car, bicycle, or walking.
- [ ] overlay at the bottom of the screen indicating "from place to destination" and how long it will take to get there with the current selected mode of transportation.

***once these features have been completed, this issue can be moved to the "In Review" board.***

**Comment by jaychenblue** [comment]
Pushed to sprint 3.

**Comment by JenYn** [comment]
Acceptance test:

- [ ] The button for the mode of travel must be highlighted when it is selected
- [ ] The directions displayed must match the selected mode
- [ ]

**Comment by JYSW380** [comment]
when doing the acceptance test, please note that we are using transit route for our shuttle bus too.
