### ISSUE TITLE
Figure out how to exclude private methods from JaCoCo

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#257]
In order to increase code coverage calculated by Jacoco, we need to excluse Private methods. This way, we get an accurate coverage. 
Private methods are currently being taken into account in the code coverage, thus decreasing our coverage percentage.

**Comment by vincentcerri** [comment]
After doing some research, private methods _should not_ be excluded from Jacoco test coverage. However, they also should not be tested directly. The correct way to do this is that private methods should automatically be called while testing the public methods of a class if all possible cases are covered.
