### ISSUE TITLE
BY-26  As a user, I want to have outdoor directions to a destination from my current location.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#26]
The app will display directions from point A to point B based on the selected mode of travel by the user and the path chosen.

This feature is related to issues #21, #22 , #23 , #25

**Comment by vincentcerri** [comment]
The final design should resemble this mockup:
![get directions mockup.PNG](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/32eba966-f7e0-4fb5-9296-03f99893ff76)

Here is the check list of features that should be included for this issue to be considered completed:
- [ ] "From" search bar
- [ ] "To" search bar
- [ ] map overlay to allow the user to switch between public transportation, car, bicycle, or walking.
- [ ] overlay at the bottom of the screen indicating "from place to destination" and how long it will take to get there with the current selected mode of transportation.
- [ ] On the map, the path that needs to be taken should be displayed and outlined using a dotted line.
- [ ] a pin should be displayed on the map signaling the destination the user is trying to reach.  

***once these features have been completed, this issue can be moved to the "In Review" board.

**Comment by jaychenblue** [comment]
This feature is going to need a lot more investigation and implementation than previously estimated.
