### ISSUE TITLE
BY-28  As a user, I want to be able to see the floor plans of the building.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#28]
Users will be able to see an overview of the floor maps by clicking on a building and choosing the option which allows them to access the floor plans. Users will be able to scroll through the floors and select the one they want to view.

This is related to issue #15

**Comment by JenYn** [comment]
![Mockups Final Final-22](https://user-images.githubusercontent.com/26283932/75601403-a9db6000-5a88-11ea-83e0-c82a34ee459a.png)

**Comment by JenYn** [comment]
**Acceptance criteria**:
- [ ] When the user clicks on a building, more information is displayed and we see the button "explore inside"
- [ ] When the user clicks on "explore inside" they see the lobby's floor plan and all of the floor numbers they can scroll through
- [ ] when the user selects a floor number, they see the floor plan of that floor 
- [ ] when the user clicks on the 'x', they are brought back to the main map

**Comment by jaychenblue** [comment]
@vicmanea @13rinda Any updates? If you're working on this, remember to link your commits to this issue number (#28).

**Comment by vicmanea** [comment]
> @vicmanea @13rinda Any updates? If you're working on this, remember to link your commits to this issue number (#28).

Brinda's branch has this working, however there is a problem with stashed Git changes, which shows up as actual code and is preventing proper runtime. I'm waiting for her to work on this together.

**Comment by vicmanea** [comment]
> > @vicmanea @13rinda Any updates? If you're working on this, remember to link your commits to this issue number (#28).
> 
> Brinda's branch has this working, however there is a problem with stashed Git changes, which shows up as actual code and is preventing proper runtime. I'm waiting for her to work on this together.

Also, the branch is running on an older version of master (with the splash screen). So ideally she needs to pull the new branch from master and copy paste her code/files on that one and then it would work. I spend a good two hours trying to do this but I can't track every change she made so it isn't working.

**Comment by SeifElDerby** [comment]
The branch was running on an older version of master (with the splash screen video). Now, the branch is updated with the new splash screen. We need to test now the code/files on that branch and check if it works or there is still the same problem.

**Comment by vicmanea** [comment]
> @vicmanea @13rinda Any updates? If you're working on this, remember to link your commits to this issue number (#28).

Yes I pushed a working version of this on the maps-overlay-v2 branch. The next steps would be to remove the conflict with the red highlight on the building, as well as linking different floor maps to different floor buttons.

**Comment by vicmanea** [comment]
> @vicmanea @13rinda Any updates? If you're working on this, remember to link your commits to this issue number (#28).

We have a working version of this now, I pushed it in the latest 'decipher-adjacent-nodes' branch. The floor buttons should pop up and disappear contextually, and when you click on them, they will display the relevant floor map overlays. Currently functioning for floor 8 and 9 in the Hall building.

**Comment by vincentcerri** [comment]
update: all that is missing is CC building

**Comment by JYSW380** [comment]
when doing acceptance test, please note that we have implement floor map only for H Building(1st floor, 8th floor and 9th floor) and CC building(CC1 and CC2).
