### ISSUE TITLE
D-22 Menu covering top of schedule

### ISSUE THREAD

**Issue by ManpreetSohal** [jaychenblue/scout-concordia#286]
**ID**: D-22
**Name**: Menu is covering the top of schedule
**Related to issue**: #113 
**Reported by**: Manpreet Sohal
**Submitted**: 2020-04-19
## **Environment**
**Device**: Galaxy A8
**API Version**: API 28
## **Details**
**Summary**: Toolbar on top covers the top of the schedule 
**Steps to reproduce**:
1. Launch the app
2. Open the Schedule page
3. Select a calendar
**Expected results**:
We expect to be able to see the top of the schedule page, but we don't.
**Actual results**:
The toolbar covers the top of the schedule. 
## **Severity**
**Severity**: Low
**Priority**: High

![image.png](https://images.zenhubusercontent.com/5c57752b39d47b774b58565e/9665973c-59e9-4e6c-8793-e18723f9d189)

**Comment by JenYn** [comment]
We now see the top of the schedule page:
![image](https://user-images.githubusercontent.com/26283932/79697152-1552da00-824f-11ea-9525-1a763d272ec5.png)
