### ISSUE TITLE
BY-29  As a user, I want interior directions for the shortest path from point A to point B.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#29]
When a user wants to get to another indoors location, when they are already inside, multiple paths are displayed and the user can choose the one they want. Shortest path is displayed when a user selects the option with the shortest ETA.

**Comment by JenYn** [comment]
implementation research:
We will have to do more research about how to implement this feature.
There are however a lot of resources online such as this one: https://developers.google.com/maps/documentation/javascript/directions

Acceptance criteria:

 - [ ] Different paths suggested with the ETA
 - [ ]Selecting the shortest path option displays the path on the map

**Comment by vincentcerri** [comment]
Update: We can now get directions from 1 class to another even if they are on different floors. There is the next button that brings the user to the next set of direction. See images.
![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/0f66f27f-25cc-49d4-8d08-fa6be503978a)
![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/3c75d552-0cb6-4b53-958a-fbf04c8515e4)
![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/deb8ffc5-dd84-49af-827b-09a83d05e39b)

**Comment by JYSW380** [comment]
when doing acceptance test, please note that we have implemented only H Building(1st floor, 8th floor and 9th floor) and CC building(CC1 and CC2).
