### ISSUE TITLE
AT-05  As a user, I want the buildings to be outlined so I can distinguish them.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#298]
User story BY-13
Issue #14 

Pertains to requirement 1.) b
“Make shapes for the campus buildings, so they are easily distinguished from the city buildings.”

**Comment by JenYn** [comment]
- [ ] Each building is outlined 
- [ ] Each building is tagged with its name

**Comment by mkshiblu** [comment]
ACCEPTED
