### ISSUE TITLE
BY-30  As a student in a wheelchair I want to find the closest elevator so I can go to a different floor easily. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#30]
Users will be able to open the floor map of the building they are in and find the shortest path to the elevator by clicking on the elevator symbol. 

This feature will be available to all users, and not those with accessibility preferences turned on

**Comment by JenYn** [comment]
**Acceptance criteria:**
- [ ] elevator symbol displayed on the elevators
- [ ] users will be able to click on the elevator symbol
- [ ] shortest path to the elevator will be displayed

**Comment by vincentcerri** [comment]
update: added a true or false variable to determine if we use disability preferences or not. If yes, the path will default to using the elevator.  If no, the path will default to using the escalator.
