### ISSUE TITLE
AT-14 As a user, I want to find the fastest path from one class to another which are in different buildings.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#302]
User story BY-22
Issue #22 

This pertains to requirement 2.)c
“Show direction on the map (using Google API)”

**Comment by JenYn** [comment]
- [ ] When searching for directions, the path is clearly shown from one class to another which are in different buildings. 
- [ ]  Path is displayed between classes on the same campus
- [ ] Pah is displayed between classes in different campuses
- [ ] Path is displayed when Walking is selected as mode of transport
- [ ] Path is displayed when Car is selected as mode of transport
- [ ] Path is displayed when Public Transit is selected as mode of transport
- [ ] Path is displayed when Shuttle bus is selected as mode of transport

**Comment by mkshiblu** [comment]
I cannot find any classroom that that is not in H-building in the search bar. How can I test this?
