### ISSUE TITLE
AT-25 As a user, I want to get directions to the location of my upcoming event.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#304]
User story BY-37
Issue #

Pertains to requirement 3.) c
“Find the location of the classroom from the next Calendar event”

**Comment by JenYn** [comment]
- [ ] Events are clickable
- [ ] User can click on “go” to get directions
- [ ] If the location of the event is not properly entered, user sees message displayed
- [ ] User can select starting point

**Comment by JenYn** [comment]
How to run this:
- Make sure to have at least one event in your calendar
- Make sure to have the location to something like H-100, CC-101, etc.
If you put in the location any other way, you will get an error message (for example h946 will not work.)

**Comment by mkshiblu** [comment]
ACCEPTED.
