### ISSUE TITLE
AT-26  As a student, I want to find the nearest washroom and/or water fountain, so that I don’t have to walk around the halls.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#305]
User story BY-40
Issue #38 

Pertains requirement 4.) d
“Highlight indoor points of interest (washrooms, water fountains, stairs, elevators)”

**Comment by JenYn** [comment]
- [ ] Washrooms, elevators, stairs, are clearly marked
(open any floor and the facilities are highlighted with the symbols.)

**Comment by mkshiblu** [comment]
ACCEPTED
