### ISSUE TITLE
AT-28 As a student I want to find the closest restaurants when I’m hungry.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#306]
User story BY-28
Issue #28 

This pertains to requirement 5.) a
“Show nearest x (or based on a range) outdoor points of interest

This pertains to requirement 5.)b
“Show directions to a selected outdoor point of interest”

**Comment by JenYn** [comment]
- [ ] Search for “restaurants near me”
- [ ] Have restaurants near the campus clearly marked with markers
- [ ] Be able to click on a marker
- [ ] Path is displayed when clicking on “go” and selecting starting location

**Comment by mkshiblu** [comment]
ACCEPTED
