### ISSUE TITLE
BY-36  As a developer, I want to be able to import a Google Calendar.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#34]
The users will be able to import their class schedule by syncing their Google Calendar to the app. This will allow them to view their schedule directly from the app and to get directions by selecting an event.

Users will have to sign in to their Google Account:
Related to issue #84 

This issue pertains the backend, thus there is not really a mockup to display that the calendar has been imported, since displaying the calendar is another issue in itself. (#130)

**Comment by JenYn** [comment]
**The users must first sign in to their google account if they haven't already**
![Google_SignIn-27 (1)](https://user-images.githubusercontent.com/26283932/75609928-cd2efb00-5ada-11ea-82a8-3e074e3aefae.png)

**The schedule will be displayed as such*
![Mockups Final Final-28](https://user-images.githubusercontent.com/26283932/75609929-ce602800-5ada-11ea-9e5a-3eab43040606.png)

**Comment by JenYn** [comment]
**Acceptance criteria**:
- [ ] The user must sign in if they have not already
- [ ] The user's google calendar is displayed on the page

**Comment by ManpreetSohal** [comment]
Implementation details:

User is requested permissions for ScoutConcordia to access their Google Calendar when signing in.
