### ISSUE TITLE
BY-37  As a user, I want to get directions to the location of my upcoming event.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#35]
Directions will be displayed based on the location of the upcoming event in the user’s Google calendar that they select.

Issue #34  must be implemented first.

**Comment by JenYn** [comment]
**Acceptance criteria**:

- [ ] The user's calendar is displayed on the page
- [ ] users can click on an event
- [ ] "Go there" button is displayed when user clicks on an event
- [ ] Directions are displayed when the user clicks on "Go There"

**Comment by jaychenblue** [comment]
@JenYn @SeifElDerby @ManpreetSohal Are their any mockups for this issue (i.e. viewing the calendar, clicking on the "go there" button, etc.)?

**Comment by SeifElDerby** [comment]
<img width="421" alt="17" src="https://user-images.githubusercontent.com/47647131/78311242-3fea2680-751e-11ea-80e2-bcaeea532c2b.png">
