### ISSUE TITLE
BY-40  As a student, I want to know where the nearest washroom and/or water fountain, so that I don’t have to walk around the halls.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#38]
Users will be able to see indoor points of interest highlighted in order to be able to clearly know where they are.

**Comment by JenYn** [comment]
We need to make these places clickable so that the user can get to them. 

Click on the icon of the washroom and you get a pop up that says ''go there from current location''.

Implementation decision: this will only work with current location

**Comment by JenYn** [comment]
Acceptance criteria:
- [ ] Have icons displaying where the washrooms are
- [ ] Have icons displaying where the Elevators are
- [ ] Have icons displaying where the escalators are

![image](https://user-images.githubusercontent.com/26283932/79075261-c4c40580-7cbf-11ea-81bd-7faa354d59b5.png)

**Comment by JenYn** [comment]
This was implemented at the same time as #28

**Comment by vincentcerri** [comment]
There are separate icons for washrooms, elevators, and escalators. These are displayed when looking at the floor maps for any building that has them.
