### ISSUE TITLE
BY-41  As a student I want to find the closest restaurants when I’m hungry.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#39]
The users will be able to search for “Restaurants near me” and have a list from which they can select a restaurant. 

Related to - [#87]

**Comment by JenYn** [comment]
![Mockups Final Final-20](https://user-images.githubusercontent.com/26283932/75610488-8263b200-5adf-11ea-9f7a-5c0b84235bff.png)

**Comment by JenYn** [comment]
**Acceptance criteria**:
- [ ] When the user inputs a query such as "Restaurants near me", they get a list of suggestions
- [ ] When the user selects a suggestion, they can get the directions to the place.

**Comment by JenYn** [comment]
This will be done with a hardcoded list, we will not be using the Google API.

''Restaurants near me '' --> list
''Entertainment near me'' --> another list 

We will then get directions to the place

**Comment by vincentcerri** [comment]
update: 

You can now use the search bar to search for the special term "restaurants near me". This will display all of the markers on the map for the restaurants. 
![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/d9f1c7e8-33ef-44a0-a535-3afe67a9e0a4)
![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/dd89715c-7230-4b85-8b89-0b6404027fd9)
![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/45395329-e3f4-4d6d-af64-f19ca8a5e345)

You can also search for a restaurant directly using the search bar as all the restaurants are now displayed within the search bar. 
![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/2b84fefe-e621-4259-a3e3-b585419fb3ce)
