### ISSUE TITLE
BY-30 As a user, I want to be able to zoom in and out of the map

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#41]
Users should be able to zoom in and out of the map.

**Comment by jaychenblue** [comment]
Manu!

**Comment by JenYn** [comment]
**Acceptance criteria:**

- [ ] User is able to pinch to zoom in and out.

**Comment by JenYn** [comment]
Note: This may not be replicated on the emulator, must be tested on a physical phone.
