### ISSUE TITLE
Map doesn't load properly when opened

### ISSUE THREAD

**Issue by jaychenblue** [jaychenblue/scout-concordia#54]
The building outlines are displayed correctly but the rest of the map doesn't load properly unless the user moves the map.

Only occurs in the emulator, not the phone. Could potentially be related to the current location.

**Repro steps:**

1. Launch the app using the emulator in Android Studio

**Results:**

The map is loaded, but only the buildings and current location are visible. The rest of map doesn't load correctly until the map is moved by the user (through dragging).

**Expected results:**

The map should appear immediately.

**Comment by jaychenblue** [comment]
![Screen Shot 2020-02-07 at 9 22 15 PM](https://user-images.githubusercontent.com/46407459/74077727-39dd3b00-49f0-11ea-93a0-dc455dda8ef4.png)

**Comment by jaychenblue** [comment]
Still reproducing this bug after the latest merge into master.

**Comment by Averynder** [comment]
Issue has been taken care of with a simple refresh for now. It should also be noted that this issue was only in the case that the location was in the Concordia region / where our custom highlighting of the buildings had occured

**Comment by jaychenblue** [comment]
What do you mean by simple refresh? The issue goes away when you move the map around.

Why is this bug in review? Should it be closed instead?
