### ISSUE TITLE
BY-3 As a user, I want to be able to sign in to my account using Google sign in to sync my school calendar.

### ISSUE THREAD

**Issue by JYSW380** [jaychenblue/scout-concordia#7]
Sign in to Google account is required in order to access Google calendars. 
 - User is only asked to sign in to Google account if they wish to sync their calendar with 
   ScoutConcordia and that they have not already signed in.
- A sign in dialog is shown only when user wishes to view their Google calendar and has not 
   signed in previously.

This will allow the user to sync their calendar to the application. Related to issue #36 

Acceptance criteria:

- [x] User is prompted to sign in to their Google Account if they click on the schedule page and they have not signed in before

Note:
We will only be able to visualize this when the schedule page is implemented.

Mockup:
![Google_SignIn-27](https://user-images.githubusercontent.com/26283932/75600334-26b40d00-5a7c-11ea-9ef5-19bce26e1f1d.png)

**Comment by jaychenblue** [comment]
The sign in branch was merged into the master. However, no prompt has been implemented yet because it should only appear when importing calendars. The actual sign in functionality is in the code and works properly on my system.

**Comment by ManpreetSohal** [comment]
Implementation details:

The sign in prompt shows all the Google accounts set on the devices and asks user with which  one to log in and also let's the user know that they will also be granting the app to access their Google calendars. Permissions are requested along the sign in as sign in is required only when access to google calendar is needed.

- Google sign in is implemented with Google Play Services auth. 
- The scope for Google calendar is requested through the GoogleSignInOptions along with 
  user's email. This grants permission to use user's google calendar.
- The project's web client Id is set as the Id token to the GoogleSignInOptions for authentication  .
