### ISSUE TITLE
BY-87  As a developer, I need to implement a navigation pane at the bottom of the app. 

### ISSUE THREAD

**Issue by jaychenblue** [jaychenblue/scout-concordia#70]
Navigate between the map, calendar schedule and shuttle bus schedule.

- [x] Investigate whether to create new activities
- [x] Investigate whether to change content views

**Comment by JenYn** [comment]
Navigation pane that will allow users to navigate.
--

**Comment by JenYn** [comment]
The Navigation pane will look like this:
![Map_Loyola-2 (1)](https://user-images.githubusercontent.com/26283932/75610942-d40e3b80-5ae3-11ea-9264-5615e1ab1315.png)

**Comment by JenYn** [comment]
Acceptance criteria:
- [ ] Navigation pane appears on the bottom of the application
- [ ] When we click on the map tab, the map page is displayed
- [ ] When we click on the shuttle schedule tab, the shuttle bus schedule is displayed
- [ ] when we click on the schedule tab, we are presented with the schedule page

**Comment by ManpreetSohal** [comment]
Implementation details:

The navigation bar is placed at the bottom of each activity view and is created using the BottomNavigationView from the Android design support library. An onNavigationItemSelected listener is set for the BottomNavigationView in each activity and it starts the activity of the navigation item selected. If navigation item selected equals the current activity, no action is taken.The MapsActivity's launch mode is set to singleTask so there is only one instance of it and the ShuttleScheduleActivity and CalendarActivity have no_history set to true. This allows the user to go to the MapsActivity when back button is pressed from either ShuttleScheduleActivity or CalendarActivity. If back button is pressed on MapsActivity, the application is sent to the background.
