### ISSUE TITLE
BY-9  As a user, I want the splash screen to be animated. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#72]
The product owner asked that the splash screen be animated instead of static.
This is an improvement and continuation of issue #8. 

Acceptance criteria: 
- [ ] The complete animation must run
- [ ] If the app is not done loading, a static version of the logo must remain on the screen until the app loads. 

Implementation strategy/requirements: 
- [ ] Need JSON format

**Comment by jaychenblue** [comment]
The loading of the video seems clunky and there's a black screen that momentarily appears. Unless this is fixed, I don't think the animated splash screen should go into master yet.

**Comment by JenYn** [comment]
Link to the splash screen mockup: https://drive.google.com/file/d/1QMSFc25wRR5AOUbzb45F_9qAM6BywoJY/view?usp=sharing

Note: The mockup is a static image just to give the developer an idea of what the final implementation will look like
