### ISSUE TITLE
BY-31 As a student, I want the target room I want to go to to be clearly marked. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#74]
The target destination room will be identified with a marker in order to make it obvious for users which room they are going to.

**Comment by JenYn** [comment]
**The final result will look like this: **
![Mockups Final Final-18](https://user-images.githubusercontent.com/26283932/75609745-239b3a00-5ad9-11ea-867e-8ff6d465b069.png)

**Comment by JenYn** [comment]
**Acceptance criteria:**

- [ ] When the user selects a destination and a path, the target room has a marker on it

**Comment by jaychenblue** [comment]
This issue can be considered an implementation detail and may not be necessary.

@vincentcerri If you're already linking your commits to another issue and this feature is already implemented, please close this issue.

**Comment by vincentcerri** [comment]
Okay this can be considered as an implementation detail for indoor directions #29 and all corresponding commits will thus be linked to #29
