### ISSUE TITLE
BY-32  As a student, I want to be able to scroll through the floors of the building. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#75]
In order to make it easier for users to select the floor they want to see, they will be able to scroll through the list of floors, since not all buildings have the same number of floors. This will ensure that all scrollbars are consistent when it comes to size and font.

**Comment by JenYn** [comment]
**the scroll bar will look like this**
![Mockups Final Final-18 (1)](https://user-images.githubusercontent.com/26283932/75609815-a15f4580-5ad9-11ea-97db-1534433197be.png)

**Comment by JenYn** [comment]
**Acceptance criteria**:
- [ ] all scrollbars of buildings are consistent in style
- [ ] if there are more than 10 floors in a building, users can scroll horizontally to reach higher ones
- [ ] When the user selects a floor, they see the floor plan on that floor.

**Comment by jaychenblue** [comment]
@vincentcerri I know you and the other implementers are already working on this. Are the commits linked to an issue? If you think this issue is redundant, please close it.

**Comment by vicmanea** [comment]
> @vincentcerri I know you and the other implementers are already working on this. Are the commits linked to an issue? If you think this issue is redundant, please close it.

Yes, this issue essentially became one and the same with [#28], and all recent commits have been pushed there. We can close this one.

**Comment by JYSW380** [comment]
when doing acceptance test, please note that we have implement only H Building(1st floor, 8th floor and 9th floor) and CC building(CC1 and CC2).
<img width="115" alt="Screen Shot 2020-03-29 at 7 43 56 PM" src="https://user-images.githubusercontent.com/41170611/77864287-a822ca80-71f5-11ea-825e-be4d3a3f6206.png">
<img width="111" alt="Screen Shot 2020-03-29 at 7 42 48 PM" src="https://user-images.githubusercontent.com/41170611/77864290-aa852480-71f5-11ea-8528-20bce2f82b5e.png">
