### ISSUE TITLE
BY-56  As a developer, I need to research how to refresh in-app. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#79]
When changing the language, I want the application to refresh automatically without me having to close and reopen.
--

**Comment by 13rinda** [comment]
This following video explains how auto-refreshing may be implemented for this application: https://www.youtube.com/watch?v=mAKyrMGgGU4

The passing criteria for this implementation are that the live data is provided instantaneously in the sense that the application is auto-refreshing every 1000 milliseconds (1 second).
