### ISSUE TITLE
BY-3  As a user, I want to see a splash screen while the app is loading.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#8]
A splash screen is displayed while the app is loading.

**Comment by jaychenblue** [comment]
Implementation is done. Waiting for the splash screen background image from Seif to finalize the feature.

**Comment by JenYn** [comment]
Link to the mockup: https://drive.google.com/file/d/1QMSFc25wRR5AOUbzb45F_9qAM6BywoJY/view?usp=sharing
