### ISSUE TITLE
BY-58  As a developer, I need to implement a search bar.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#81]
Search bar to search locations.
Needs to be overlayed over the map

**Comment by vincentcerri** [comment]
The final design should resemble this mockup:
![search bar mockup.PNG](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/b490d579-7680-4b3a-bd5b-bf5f3d8367c4)

Here is the checklist of features that should be included for this issue to be considered completed: 
- [ ] Search bar is displayed at the top of the map (right above the toggle switch) 
- [ ] When I tap on the search bar, a keyboard will appear allowing me to type.
- [ ] After entering a location and pressing search (the magnifying glass icon), the map will zoom and center based on the searched location. 
- [ ] If I press on the "X" button, the search bar will be cleared. 

***once these features have been completed, this issue can be moved to the "In Review" board.***

**Comment by JenYn** [comment]
Implementation strategy:

In order to implement this feature, we will use Places SDK for android. 
The documentation used for this feature can be found at this link: https://developers.google.com/places/android-sdk/intro

**Comment by jaychenblue** [comment]
Search bar is displayed, but no results are displayed when I start typing. I think this is to be expected since the actual backend search results will come later.

**Comment by JenYn** [comment]
Search bar is displayed and we can input an address. The map will zoom and center on the location entered. 

![image](https://user-images.githubusercontent.com/26283932/75587235-06685c00-5a44-11ea-83b8-b9bccd83eb11.png)

![image](https://user-images.githubusercontent.com/26283932/75587245-0cf6d380-5a44-11ea-878a-578143c51d31.png)

**Comment by JenYn** [comment]
Note: This feature does not include the following

- Displaying recently searched locations [see issue #73]
- Displaying nearby locations [see issue #87]
- Displaying Concordia specific locations [see issue #83]

**Comment by JenYn** [comment]
We modified the mockup to match what was implemented. We are focusing on functionality rather than styling for this sprint. 


![Mockups Final Final-02 (1)](https://user-images.githubusercontent.com/26283932/75593448-65819d00-5a53-11ea-9dc3-5022c704c86c.png)
