### ISSUE TITLE
Modify the search bar to search for nearby locations. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#87]
This is a continuation of BY-58 [#81 ].

Users should be able to search for locations nearby using queries such as "Restaurant near me". 

Checklist of features that should be included for this issue to be considered completed: 

- [ ] Can search for restaurants near the user
- [ ] Have a list of locations nearby corresponding to the query 
- [ ] Map has to zoom and center on chosen location

**Once these features have been completed, this issue can be moved to the "In review" Pipeline.

**Comment by JenYn** [comment]
Implementation strategy: 

The following documentation will be used in order to implement this feature. 
https://developers.google.com/places/web-service/query

**Comment by jaychenblue** [comment]
@JenYn Is this done?

**Comment by JenYn** [comment]
This is a duplicate of issue #39, we are therefore closing it.
